# @package _group_
train:
  augs:
    - class_name: albumentations.Resize
      params:
        height: 512
        width: 512
#    - class_name: albumentations.Normalize
#      params:
#        mean: [ 0.485, 0.456, 0.406 ]
#        std: [ 0.229, 0.224, 0.225 ]
#        p: 1.0
#    - class_name: albumentations.pytorch.transforms.ToTensorV2
#      params:
#        p: 1.0
  siamese:
    - class_name: albumentations.Resize
      params:
          height: 512
          width: 512
    - class_name: albumentations.Cutout
      params:
        num_holes: 3
        max_h_size: 16
        max_w_size: 40
        fill_value: 0
        p: 1.0
    - class_name: albumentations.ShiftScaleRotate
      params:
        shift_limit: 0.0625
        scale_limit: 0.1
        rotate_limit: 10
    - class_name: albumentations.RandomBrightnessContrast
      params:
        p: 1.0
    - class_name: albumentations.OneOf
      params:
        - class_name: albumentations.RGBShift
          params:
            p: 1.0
        - class_name: albumentations.HueSaturationValue
          params:
            p: 1.0

    - class_name: albumentations.HorizontalFlip
      params:
        p: 0.5
#    - class_name: albumentations.Normalize
#      params:
#        mean: [ 0.485, 0.456, 0.406 ]
#        std: [ 0.229, 0.224, 0.225 ]
#        p: 1.0
  #    - class_name: albumentations.pytorch.transforms.ToTensorV2
  #      params:
  #        p: 1.0
valid:
  augs:
  - class_name: albumentations.Resize
    params:
      height: 512
      width: 512
  - class_name: albumentations.Normalize
    params:
      mean: [ 0.485, 0.456, 0.406 ]
      std: [ 0.229, 0.224, 0.225 ]
      p: 1.0
  - class_name: albumentations.pytorch.transforms.ToTensorV2
    params:
      p: 1.0