defaults:
  - datamodule: ade20k
  - trainer: default_trainer
  - training: default_training
#  - logging: tensorboard
#  - optimizer: sgd
#  - scheduler: plateau
#  - model: simple_model
#  - callbacks: callbacks
  - augmentation: basic_augs
#  - loss: cross_entropy
#  - metric: accuracy
  - hydra/hydra_logging: default
  - hydra/job_logging: disabled

pretty_print: True

general:
  run_name: ${now:%Y-%m-%d_%H-%M-%S}
  run_dir: outputs/${general.run_name}
  logs_folder_name: logs
  logs_dir: ${general.run_dir}/${general.logs_folder_name}
#  workspace: slam
  project_name: lg-net
  device: cuda
  log_code: True
  save_pytorch_model: True

hydra:
  run:
    dir: .
  sweep:
    dir: .
  output_subdir: outputs/${now:%Y-%m-%d_%H-%M-%S}/.hydra