# @package _group_
log: True
loggers:
  - class_name: lg_net.utils.loggers.CsvLogger
    params:
      csv_path: ${general.logs_dir}/csv_log.csv

  - class_name: pl.loggers.TensorBoardLogger
    params:
      save_dir: .
      name: ${general.run_dir}

  - class_name: pl.loggers.CometLogger
    params:
      save_dir: ${general.logs_folder_name}
      workspace: ${general.workspace}
      project_name: ${general.project_name}
      api_key: ${private.comet_api}
      experiment_name: ${general.run_name}